services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: LPDigital-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - db-data:/usr/src/app/prisma/data
      - ./backend/public/documents:/usr/src/app/public/documents

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Reicht VITE_API_BASE_URL aus der frontend/.env an Vite beim Bauen weiter!
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: LPDigital-frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend

volumes:
  db-data: