name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Oder 'master'

# WICHTIG: Berechtigungen für das GITHUB_TOKEN setzen
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/musictogetcodedon/lpdigital-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args: |
            VITE_API_BASE_URL=https://api.lpdigital.ch
          push: true
          tags: ghcr.io/musictogetcodedon/lpdigital-frontend:latest